[package]
name = "example"
version = "0.1.0"
authors = ["kydos <angelo@icorsaro.net>"]
publish = false
edition = "2018"

[dev-dependencies]
dds = { path = "../dds" }


[[example]]
name = "pub"
path = "pub.rs"
