[package]
name = "examples"
version = "0.1.2"
authors = ["kydos <angelo@icorsaro.net>"]
publish = false
edition = "2018"

[dev-dependencies]
ddsc = { path = ".." }

[[example]]
name = "discoverer"
path = "discovere.rs"
