name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Run cargo check
      uses: actions-rs/cargo@v1
      with:
        command: check

    - name: Build
      run: cargo build --verbose --all-targets
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --verbose --all-targets

    - name: Clippy
    - name: Clippy
      run: cargo clippy --all --examples
      uses: actions-rs/cargo@v1
      with:
        command: clippy
        args: --all --examples

    - name: Run tests
    - name: Run tests
      run: cargo test --verbose
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --verbose
